print("Old MacDonald had a farm, E-I-E-I-O")
print("And on his farm he had a pig, E-I-E-I-O")
print("With a Oink Oink here, and a Oink Oink there")
print("Here a Oink, there a Oink everywhere a Oink Oink")
print("Old MacDonald had a farm E-I-E-I-O")
print("")print("Old MacDonald had a farm, E-I-E-I-O")
print("And on his farm he had a cow, E-I-E-I-O")
print("With a Moo Moo here, and a Moo Moo there")
print("Here a Moo, there a Moo everywhere a Moo Moo")
print("Old MacDonald had a farm E-I-E-I-O")
